name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_USERNAME}}/marketboro
      - name: Push Docker image
        run: docker push ${{secrets.DOCKER_USERNAME}}/marketboro
      - name: create pem file
        run: 'echo "$PEM" > doyoung.pem'
        env:
          PEM: ${{EC2_PEM}}
      - name: access ec2
        run: ssh -i "doyoung.pem" ubuntu@ec2-13-124-99-233.ap-northeast-2.compute.amazonaws.com
