name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: create backend .env
        run: 'echo "$BACKEND_ENV" | base64 --decode > ./backend/.env' 
        env:
          BACKEND_ENV: ${{secrets.BACKEND_ENV}}

      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_USERNAME}}/marketboro
      - name: Push Docker image
        run: docker push ${{secrets.DOCKER_USERNAME}}/marketboro

      - name: docker-compose restart
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: sudo docker-compose down && sudo docker rmi jispoop/marketboro && sudo docker-compose up -d
          host: ec2-13-124-99-233.ap-northeast-2.compute.amazonaws.com
          username: ubuntu
          privateKey: ${{secrets.EC2_PEM}}
