name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      # - uses: actions/checkout@v2
      # - name: Login to DockerHub
      #   run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      # - name: Build the Docker image
      #   run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_USERNAME}}/marketboro
      # - name: Push Docker image
      #   run: docker push ${{secrets.DOCKER_USERNAME}}/marketboro
      - name: create pem file
        env:
          PEM: ${{secrets.EC2_PEM}}
        run: 'echo "$PEM" > doyoung.pem'
      - name: pem chmod
        run: chmod 400 doyoung.pem
      - name: ls
        run: ls
      - name: access ec2
        run: ssh -i "doyoung.pem" ubuntu@ec2-13-124-99-233.ap-northeast-2.compute.amazonaws.com

      - name: ls -a via ssh
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: ls -a
          host: ec2-13-124-99-233.ap-northeast-2.compute.amazonaws.com
          username: ubuntu
          # passphrase: ${{ secrets.PASSPHRASE }}
          privateKey: ${{secrets.EC2_PEM}}
